### ISSUE TITLE
Issues while setting hostname to dns hostname instead of "*" in the virtual servicec

### ISSUE THREAD

**Issue by syamrag** [zioproto/istio-aks-example#3]
I have followed the configuration and I was able to access the service by using hostname if I use the below configuration.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-virtual-service
spec:
  hosts:
    - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:

    - uri:
        prefix: "/"

    route:
    - destination:
        host: nginx-service.default.svc.cluster.local
        port:
          number: 8080
```
 But If I add a external hostname to the hostname field the service is not loading. Here is my other configurations for AFD helath prob.  

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
```
---
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: healthcheck
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: "/probe"
    rewrite:
        uri: "/healthz/ready"
    route:
    - destination:
        host: "istio-ingressgateway.istio-system.svc.cluster.local"
        port:
          number: 15021
```
